export const PUBLIC_URL = process.env.PUBLIC_URL;
export const MAINTENANCE_MODE =
  process.env.REACT_APP_MAINTENANCE_MODE === "true";

// env
//
export const CDM_ENV_NAME = process.env.REACT_APP_ENV_NAME;

// services
//
export const CDM_TRANSFORMATION_PROCESSING_SERVICE_URI =
  process.env.REACT_APP_CDM_TRANSFORMATION_PROCESSING_SERVICE_URI;
export const CDM_BUSINESS_RULES_MGMNT =
  process.env.REACT_APP_CDM_BUSINESS_RULES_MGMNT_URI;
export const CDM_BUSINESS_RULES_EVAL =
  process.env.REACT_APP_CDM_BUSINESS_RULES_EVAL_URI;
export const CDM_TRANSFORMATION_MANAGEMENT_SERVICE_URI =
  process.env.REACT_APP_CDM_TRANSFORMATION_MANAGEMENT_SERVICE_URI;
export const CDM_TRADE_ITEM_INDEXER_URI =
  process.env.REACT_APP_CDM_TRADE_ITEM_INDEXER_URI;
export const CDM_AUTH_URI = process.env.REACT_APP_CDM_AUTH_URI;
export const CDM_LOGISTIC_URI = process.env.REACT_APP_CDM_LOGISTIC_URI;
export const CDM_PRICING_URI = process.env.REACT_APP_CDM_PRICING_URI;
export const CDM_ACKNOWLEDGEMENT_URI =
  process.env.REACT_APP_CDM_ACKNOWLEDGEMENT_SERVICE_URI;
export const CDM_STORAGE_SERVICE_URI =
  process.env.REACT_APP_CDM_STORAGE_SERVICE_URI;
export const CDM_PRE_COMPUTING_SERVICE_URI =
  process.env.REACT_APP_CDM_PRE_COMPUTING_SERVICE_URI;
export const CDM_TRADE_ITEM_PROPERTIES_SERVICE_URI =
  process.env.REACT_APP_CDM_TRADE_ITEM_PROPERTIES_SERVICE_URI;
export const CDM_TRIGGER_MANAGEMENT_SERVICE =
  process.env.REACT_APP_CDM_TRIGGER_MANAGEMENT_SERVICE;
export const CDM_EXPORT_STATISTICS_URI =
  process.env.REACT_APP_CDM_EXPORT_STATISTICS_URI;
export const CDM_IMPORT_RESOURCE_URI =
  process.env.REACT_APP_CDM_IMPORT_RESOURCE_URI;
export const CDM_IMPORT_SERVICE_URI =
  process.env.REACT_APP_CDM_IMPORT_SERVICE_URI;
export const CDM_GENERATE_PDF = process.env.REACT_APP_CDM_GENERATE_PDF;
export const CDM_EXPORT_VIDEO = process.env.REACT_APP_CDM_EXPORT_VIDEO;
export const CDM_MANUFACTURER_MANAGEMENT_URI =
  process.env.REACT_APP_CDM_MANUFACTURER_MANAGEMENT_URI;
export const CDM_TARGET_MARKET_URI =
  process.env.REACT_APP_CDM_TARGET_MARKET_URI;
export const CDM_RETAILER_MGMNT_SERVICE_URI =
  process.env.REACT_APP_CDM_RETAILER_MGMNT_SERVICE_URI;
export const CDM_USER_URI = process.env.REACT_APP_CDM_USER_URI;
export const CDM_AUDIT_SERVICE_URI =
  process.env.REACT_APP_CDM_AUDIT_SERVICE_URI;
export const CDM_TRADE_ITEM_STATS_SERVICE_URI =
  process.env.REACT_APP_CDM_TRADE_ITEM_STATS_SERVICE_URI;
export const REACT_APP_CDM_TRADE_ITEM_TRANSFORMATIONS_SERVICE_URI =
  process.env.REACT_APP_CDM_TRADE_ITEM_TRANSFORMATIONS_SERVICE_URI;
export const CDM_MATRIX_VALIDATION_SERVICE_URI =
  process.env.REACT_APP_CDM_MATRIX_VALIDATION_SERVICE_URI;
export const CDM_BUSINESS_RULE_EVAL_SERVICE_URI =
  process.env.REACT_APP_CDM_BUSINESS_RULE_EVAL_SERVICE_URI;
export const CDM_SUBSCRIPTION_SERVICE_URI =
  process.env.REACT_APP_CDM_SUBSCRIPTION_SERVICE_URI;
export const CDM_ENRICHMENT_REQUEST_SERVICE_URI =
  process.env.REACT_APP_CDM_ENRICHMENT_REQUEST_SERVICE_URI;
export const CDM_TRADE_ITEM_ELIGIBILITY_NETWORK_URI =
  process.env.REACT_APP_CDM_TRADE_ITEM_ELIGIBILITY_NETWORK_URI;
export const CDM_BUSINESS_RULE_MGMT_SERVICE_URI =
  process.env.REACT_APP_CDM_BUSINESS_RULE_MGMT_SERVICE_URI;
export const CDM_FORMAT_MANAGEMENT_SERVICE_URI =
  process.env.REACT_APP_CDM_FORMAT_MANAGEMENT_SERVICE_URI;
export const CDM_COLLECTION_SERVICE_URI =
  process.env.REACT_APP_CDM_COLLECTION_SERVICE_URI;
export const CDM_MESSAGING_SERVICE_URI =
  // "http://localhost:5045";
  process.env.REACT_APP_CDM_MESSAGING_SERVICE_URI;
export const CDM_MATRIX_MAPPING_URI =
    process.env.REACT_APP_CDM_MATRIX_MAPPING_URI;

// auth
//
export const CDM_AUTH_CLIENT_ID = process.env.REACT_APP_CDM_AUTH_CLIENT_ID;
export const CDM_AUTH_CLIENT_SECRET =
  process.env.REACT_APP_CDM_AUTH_CLIENT_SECRET;
export const CDM_AUTH_GRANT_TYPE = process.env.REACT_APP_CDM_AUTH_GRANT_TYPE;

// lang
//
export const CDM_AVAILABLE_LANG = ["en-GB", "fr-FR", "it-IT"];
export const CDM_DEFAULT_LANG =
  process.env.REACT_APP_CDM_DEFAULT_LANG || "fr-FR";

// local storage prefix
//
export const CDM_LOCAL_STORAGE_PREFIX =
  process.env.REACT_APP_CDM_LOCAL_STORAGE_PREFIX || "";

export const CDM_VARIANT_URL = process.env.REACT_APP_CDM_VARIANT_URL || "";

export const CDM_ENRICHMENT_SERVICE_URI =
  process.env.REACT_APP_CDM_ENRICHMENT_SERVICE_URI;

export const CDM_DIGITAL_ASSET_INDEXATION_SERVICE_URI =
  process.env.REACT_APP_CDM_DIGITAL_ASSET_INDEXATION_SERVICE_URI;

export const CDM_SETTING_SERVICE_URI =
  process.env.REACT_APP_CDM_SETTING_SERVICE_URI;
export const CDM_INDEXERS_SERVICE_URI =
  process.env.REACT_APP_CDM_INDEXERS_SERVICE_URI;
