export const TAXONOMIES_SUCCESS = "TAXONOMIES_SUCCESS";
export const TAXONOMIES_FAILURE = "TAXONOMIES_FAILURE";
export const TAXONOMIES_REQUEST = "TAXONOMIES_REQUEST";
export const TAXONOMIES_RESET = "TAXONOMIES_RESET";

export const TRADE_ITEM_CATEGORIES_SUCCESS = "TRADE_ITEM_CATEGORIES_SUCCESS";
export const TRADE_ITEM_CATEGORIES_FAILURE = "TRADE_ITEM_CATEGORIES_FAILURE";
export const TRADE_ITEM_CATEGORIES_REQUEST = "TRADE_ITEM_CATEGORIES_REQUEST";
export const TRADE_ITEM_CATEGORIES_RESET = "TRADE_ITEM_CATEGORIES_RESET";

export const TRANSFORMATION_SET_RECEIVE = "TRANSFORMATION_SET_RECEIVE";
export const TRANSFORMATION_SET_UPDATE = "TRANSFORMATION_SET_UPDATE";
export const TRANSFORMATION_SET_PUSH_NEW_TRANSFORMATION =
  "TRANSFORMATION_SET_PUSH_NEW_TRANSFORMATION";
export const TRANSFORMATION_SET_TRANSFORMATION_SELECTED =
  "TRANSFORMATION_SET_TRANSFORMATION_SELECTED";
export const TRANSFORMATION_SET_DELETE_TRANSFORMATION =
  "TRANSFORMATION_SET_DELETE_TRANSFORMATION";

export const TRANSFORMATION_SET_ACTION_SET_SELECTED =
  "TRANSFORMATION_SET_ACTION_SET_SELECTED";
export const TRANSFORMATION_SET_ACTION_RECEIVED =
  "TRANSFORMATION_SET_ACTION_RECEIVED";

export const TRANSFORMATION_SET_ACTION_INDEX_SELECTED =
  "TRANSFORMATION_SET_ACTION_INDEX_SELECTED";
export const TRANSFORMATION_SET_PUSH_NEW_ACTION_SET =
  "TRANSFORMATION_SET_PUSH_NEW_ACTION_SET";
export const TRANSFORMATION_SET_PUSH_ACTION_RECEIVE =
  "TRANSFORMATION_SET_PUSH_ACTION_RECEIVE";
export const TRANSFORMATION_SET_PUSH_ACTION_UPDATE =
  "TRANSFORMATION_SET_PUSH_ACTION_UPDATE";

export const TRADE_ITEMS_PROPERTIES_SUCCESS = "TRADE_ITEMS_PROPERTIES_SUCCESS";
export const TRADE_ITEMS_PROPERTIES_FAILURE = "TRADE_ITEMS_PROPERTIES_FAILURE";
export const TRADE_ITEMS_PROPERTIES_REQUEST = "TRADE_ITEMS_PROPERTIES_REQUEST";
export const TRADE_ITEMS_PROPERTIES_RESET = "TRADE_ITEMS_PROPERTIES_RESET";

export const TRANSFORMATION_SET_PLAYGROUND_TRADE_ITEM_SELECTED =
  "TRANSFORMATION_SET_PLAYGROUND_TRADE_ITEM_SELECTED";
export const TRANSFORMATION_SET_PLAYGROUND_RESULT =
  "TRANSFORMATION_SET_PLAYGROUND_RESULT";
export const INITIALIZE_TRADE_ITEM_TRANSFORMATION =
  "INITIALIZE_TRADE_ITEM_TRANSFORMATION";
export const PROPERTY_GROUP_LOADER = "PROPERTY_GROUP_LOADER";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const BUSINESS_SET_RULES = "BUSINESS_SET_RULES";
export const TRADE_ITEMS_PROPERTIES = "TRADE_ITEMS_PROPERTIES";
export const GET_ACTION_DEFINITIONS = "GET_ACTION_DEFINITIONS";
export const SELECTED_ACTION_INDEX = "SELECTED_ACTION_INDEX";
export const SET_ACTION = "SET_ACTION";
export const ACTION_SET_DATA = "ACTION_SET_DATA";
export const SET_TRANSFORMATION_ACTION_SET = "SET_TRANSFORMATION_ACTION_SET";
export const SELECTED_ACTION_SET_INDEX = "SELECTED_ACTION_SET_INDEX";
export const SELECTED_TRANSFORMATION_INDEX = "SELECTED_TRANSFORMATION_INDEX";
export const GET_PROPERTY_GROUPS = "GET_PROPERTY_GROUPS";
export const GET_TRADE_ITEM_TRANSFORMATION = "GET_TRADE_ITEM_TRANSFORMATION";
export const SET_TRADE_ITEM_TRANSFORMATION = "SET_TRADE_ITEM_TRANSFORMATION";

export const CDM_SUBSCRIPTION_OFFER_DATA = "CDM_SUBSCRIPTION_OFFER_DATA";
export const CDM_CREATE_OFFER_REQUEST = "CDM_CREATE_OFFER_REQUEST";
export const CDM_CREATE_OFFER_FAILURE = "CDM_CREATE_OFFER_FAILURE";
export const CDM_CREATE_OFFER_SUCCESS = "CDM_CREATE_OFFER_SUCCESS";
export const CDM_SUBSCRIPTION_OFFER_DATA_LIST = "CDM_SUBSCRIPTION_OFFER_DATA_LIST";
export const CDM_SUBSCRIPTION_SINGLE_OFFER_DATA = "CDM_SUBSCRIPTION_SINGLE_OFFER_DATA";
export const CDM_SUBSCRIPTION_LIST_LOADER = "CDM_SUBSCRIPTION_LIST_LOADER";
export const CDM_MANUFACTURER_DATA = "CDM_MANUFACTURER_DATA";
export const CDM_SUBSCRIPTIONS_DATA = "CDM_SUBSCRIPTIONS_DATA";
export const CDM_SUBSCRIPTIONS_FAILURE = "CDM_SUBSCRIPTIONS_FAILURE";
export const CDM_CONNECTORS_DATA = "CDM_CONNECTORS_DATA";
export const CDM_CONNECTIONS_DATA = "CDM_CONNECTIONS_DATA";
export const CDM_CONNECTIONS_FAILURE = "CDM_CONNECTIONS_FAILURE";
export const CDM_CONNECTIONS_SUCCESS = "CDM_CONNECTIONS_SUCCESS";
export const CDM_CONNECTIONS_LOADER = "CDM_CONNECTIONS_LOADER";

export const CDM_CONNECTORS_FAILURE = "CDM_CONNECTORS_FAILURE";
export const CDM_CONNECTORS_SUCCESS = "CDM_CONNECTORS_SUCCESS";
export const CDM_CONNECTORS_LOADER = "CDM_CONNECTORS_LOADER";

export const CDM_TARGETMARKETS_DATA = "CDM_TARGETMARKETS_DATA";
export const CDM_RETAILER_DATA = "CDM_RETAILER_DATA";
export const CDM_SET_CONNECTORS_DATA = "CDM_SET_CONNECTORS_DATA";

export const CDM_SET_CONNECTORS_MASS_TOOLS_DATA ="CDM_SET_CONNECTORS_MASS_TOOLS_DATA";
export const CDM_CONNECTORS_IN_MASS_LOADER = "CDM_CONNECTORS_IN_MASS_LOADER";
export const CDM_CONNECTORS_IN_MASS_SUCCESS = "CDM_CONNECTORS_IN_MASS_SUCCESS";
export const CDM_CONNECTORS_IN_MASS_FAILURE = "CDM_CONNECTORS_IN_MASS_FAILURE";

export const CDM_SET_CONNECTIONS_MASS_TOOLS_DATA ="CDM_SET_CONNECTIONS_MASS_TOOLS_DATA";
export const CDM_CONNECTIONS_IN_MASS_LOADER = "CDM_CONNECTIONS_IN_MASS_LOADER";
export const CDM_CONNECTIONS_IN_MASS_SUCCESS = "CDM_CONNECTIONS_IN_MASS_SUCCESS";
export const CDM_CONNECTIONS_IN_MASS_FAILURE = "CDM_CONNECTIONS_IN_MASS_FAILURE";

export const CDM_RETAILER_OBJECT_DATA = "CDM_RETAILER_OBJECT_DATA";
export const APP_RETAILERS_GROUPS_LIST = "APP_RETAILERS_GROUPS_LIST";

export const CDM_RETAILER_LOADER = "CDM_RETAILER_LOADER";
export const CDM_RETAILER_SUCCESS = "CDM_RETAILER_SUCCESS";
export const CDM_RETAILER_FAILURE = "CDM_RETAILER_FAILURE";

export const GET_EXPORT_ACTION_DATA = "GET_EXPORT_ACTION_DATA";

export const APP_MANUFACTURERS_DATA = "APP_MANUFACTURERS_DATA";
export const TAXONOMIES_DATA = "TAXONOMIES_DATA";
export const BUSINESS_RULES_SET_DATA = "BUSINESS_RULES_SET_DATA";
export const APP_MANUFACTURERS_PDF_DATA = "APP_MANUFACTURERS_PDF_DATA";
export const APP_MANUFACTURERS_ENTITIES_DATA = "APP_MANUFACTURERS_ENTITIES_DATA";
export const APP_MANUFACTURERS_MATRIX_MAPPING_DATA ="APP_MANUFACTURERS_MATRIX_MAPPING_DATA";
export const APP_MANUFACTURERS_IMAGE_CATEGORIES_DATA ="APP_MANUFACTURERS_IMAGE_CATEGORIES_DATA";
export const APP_MANUFACTURERS_LANGUAGES_DATA = "APP_MANUFACTURERS_LANGUAGES_DATA";

export const APP_GET_ALL_RETAILER_DATA = "APP_GET_ALL_RETAILER_DATA";
export const APP_ENRICHMENT_CONFIGURATIONS_DATA = "APP_ENRICHMENT_CONFIGURATIONS_DATA";
